# saves the url to the database
bad_sites = {'24sevendailynews.com':8,
             "akoy-pilipino.blogspot.com":-1,
             "aljazeera-tv.com":7,
             "allthingspinoy.com":23,
             "asianpolicy.press":0,
             "www.balitangpinas.net":2,
             "bbc101.co.uk":-1,
             "bbctimes.com":3,
             "latestdutertenews.altervista.org":0,
             "classifiedtrends.net":19,
             "cnnalive.com":-1,
             "da1lymail.com":6,
             "dai1lymail.co.uk":-1,
             "dailyfilipino.altervista.org":-1,
             "dailyfilipinews.blogspot.com":-1,
             "definitelyfilipino.com":103,
             "balita.definitelyfilipino.com":-1,
             "buzz.definitelyfilipino.com":-1,
             "dugongmaharlika.com":0,
             "dutertenews.com":22,
             "du30news.com":5,
             "du30news.net":11,
             "www.dutertenewswatch.com":8,
             "du30newsblog.blogspot.com":-1,
             "du30newsinfo.com":19,
             "dutertetrendingnews.blogspot.com":-1,
             "www.dyaryo.net":19,
             "dutertedefender.com":17,
             "extremereaders.com":32,
             "filipinewsph.net":11,
             "grpshorts.blogspot.com":-1,
             "theguard1an.com":18,
             "hotnewsphil.blogspot.com":-1,
             "www.iampilipino.com":24,
             "www.leaknewsph.com":6,
             "www.maharlikanews.com":24,
             "mindanation.com":67,
             "okd2.com":29,
             "ilikeyouquotes.blogspot.com":-1,
             "philnewscourier.blogspot.com":-1,
             "www.philnewsportal.com":4,
             "pilipinastrendingnews.blogspot.com":-1,
             "pinasnewsportal.blogspot.com":-1,
             "pinoyfreedomwall.com":-1,
             "pinoynewsblogger.blogspot.com":-1,
             "pinoynewstv.com":2,
             "pinoypasikat.tk":-1,
             "pinoyspeak.info":10,
             "pinoyviralissues.net":4,
             "pinoyworld.net":26,
             "phppoliticsnews.blogspot.com":-1,
             "pinoytrending.altervista.org":-1,
             "pinoytrendingnews.net":30,
             "pinoytrendingnewsph.blogspot.com":-1,
             "pinoytrending.altervista.org":-1,
             "pinoyviralissues.net":-1,
             "pinoyworld.net":26,
             "publictrending.net":-1,
             "publictrending.news":0,
             "qwazk.blogspot.com":-1,
             "radiogtv.com":7,
             "sowhatsnews.wordpress.com":-1,
             "www.socialnewsph.com":19,
             "tahonews.com":40,
             "thenewsfeeder.net":9,
             "thephilippinepolitics.com":8,
             "thet1mes.com":18,
             "thevolatilian.com":22,
             "thinkingpinoy.net":24,
             "thinkingpinoynews.info":10,
             "todayinmanila.ga":-1,
             "trendingnewsportal.com":69,
             "trendingnewsportal.net":27,
             "trendingnewsportal.net.ph":-1,
             "trendingnewsportal.blogspot.com":-1,
             "blogspot.com":-1,
             "tnp.today":0,
             "trendingnewsvideo.com":-1,
             "trendingtopics.altervista.org":-1,
             "trendingviral.tk":0,
             "radio.com":259,
             "verifiedph.blogspot.com":-1,
             "viralportal.ml":0,
             "http://ww6.365usnews.com":1}


# see if the given link is in the bad sites list
def find_in_db(u):
    return str(u.strip().replace('\n', '')) in bad_sites

def find_time_link(address):
    bad_sites[address]
