# saves the url to the database
bad_sites = ["24sevendailynews.com",  # WORKS
             "hotnewsphil.blogspot.com",  # WORKS
             "akoy-pilipino.blogspot.com",
             "aljazeera-tv.com",
             "allthingspinoy.com",
             "asianpolicy.press",
             "www.balitangpinas.net",
             "bbc101.co.uk",
             "bbctimes.com",
             "latestdutertenews.altervista.org",
             "classifiedtrends.net",
             "cnnalive.com",
             "da1lymail.com",
             "dai1lymail.co.uk",
             "dailyfilipino.altervista.org",
             "dailyfilipinews.blogspot.com",
             "definitelyfilipino.com",
             "balita.definitelyfilipino.com",
             "buzz.definitelyfilipino.com",
             "buzz.definitelyfilipino.net",
             "dugongmaharlika.com",
             "dutertenews.com",
             "du30news.com",
             "du30news.net",
             "www.dutertenewswatch.com",
             "du30newsblog.blogspot.com",
             "du30newsinfo.com",
             "dutertetrendingnews.blogspot.com",
             "www.dyaryo.net",
             "dutertedefender.com",
             "extremereaders.com",
             "filipinewsph.net",
             "grpshorts.blogspot.com",
             "theguard1an.com",
             "hotnewsphil.blogspot.com",  # WORKS
             "www.iampilipino.com",
             "www.leaknewsph.com",
             "www.maharlikanews.com",
             "mindanation.com",
             "okd2.com",
             "ilikeyouquotes.blogspot.com",
             "philnewscourier.blogspot.com",
             "www.philnewsportal.com",
             "pilipinastrendingnews.blogspot.com",
             "pinasnewsportal.blogspot.com",
             "pinoyfreedomwall.com",
             "pinoynewsblogger.blogspot.com",
             "pinoynewstv.com",
             "pinoypasikat.tk",
             "pinoyspeak.info",
             "pinoyviralissues.net",
             "pinoyworld.net",
             "phppoliticsnews.blogspot.com",
             "pinoytrending.altervista.org",
             "pinoytrendingnews.net",
             "pinoytrendingnewsph.blogspot.com",
             "pinoytrending.altervista.org",
             "pinoyviralissues.net",
             "pinoyworld.net",
             "publictrending.net",
             "publictrending.news",
             "qwazk.blogspot.com",
             "radiogtv.com",
             "sowhatsnews.wordpress.com",
             "www.socialnewsph.com",
             "tahonews.com",
             "thenewsfeeder.net",
             "thephilippinepolitics.com",
             "thet1mes.com",
             "thevolatilian.com",
             "thinkingpinoy.net",
             "thinkingpinoynews.info",
             "todayinmanila.ga",
             "trendingnewsportal.com",
             "trendingnewsportal.net",
             "trendingnewsportal.net.ph",
             "trendingnewsportal.blogspot.com",
             "blogspot.com",
             "tnp.today",
             "trendingnewsvideo.com",
             "trendingtopics.altervista.org",
             "trendingviral.tk",
             "radio.com",
             "verifiedph.blogspot.com",
             "viralportal.ml",
             "http://ww6.365usnews.com"]


# see if the given link is in the bad sites list
def find_in_db(u):
    return str(u.strip().replace('\n', '')) in bad_sites

